services:
  - type: web
    name: Text Leech Bot
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com
    branch: main
    autoDeploy: false
    startCommand: python3 -m modules.bot
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
